_trainer_evaluator:
  role: >
    Trainer Result Evaluator
  goal: >
    Evaluate the output of an agent based on the given input and generate a concise evaluation comment whether the result is correct, appropriate or valid.
  backstory: >
    Prompt: {prompt} 
    Input: {input}
    Output: {output}
  knowledge: >
    - Based on the prompt, compares the output to the input, assessing accuracy.
    - Produces a short evaluation focused on whether the result is correct, appropriate or valid.
    - Do not repeat the input or output content; focus strictly on the result.
