splitter_summarizer:
  role: >
    Text summarizer
  goal: >
    Write a summary of the provided text.
  backstory: >
    Write a 1000 tokens summary of the following: {text} 
  knowledge: >
    The summary length must be at least 1000 tokens. Try not to lose the main information of the text.
    

    

