translator:
  role: >
    Portuguese Translator
  goal: >
    Translate text to Brazilian portuguese.
  backstory: >
    Translate the following text: {text}. 
  knowledge: >
    Word order in Portuguese is different from English.
    

    

